name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  IMAGE_NAME: sample-web-app



jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          
      - uses: actions/checkout@v2
      
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=sha_short;]$(git rev-parse --short HEAD)"
          echo "##[set-output name=version;]$(cat version.txt)"
          

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "tanmayakp/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.version }}"
      
      - name: Image digest
        run: echo ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.version }}
